name: agora_rtm
description: Flutter plugin for Agora RTM SDK. 1.4.1
version: 0.0.4
homepage: https://www.agora.io
repository: https://github.com/nic1207/flutter_agora_rtm_1_4_1/

environment:
  sdk: ">=2.7.0 <3.0.0"
  #flutter: ">=1.12.13+hotfix.6"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.agora.agorartm
        pluginClass: AgoraRtmPlugin
      ios:
        pluginClass: AgoraRtmPlugin
